.TH "exceltex" "1" "17. Februar, 2006" "version 0.4.0" "USER COMMANDS"

.SH "NAME"
exceltex \- Zugriff auf Exceldateien aus LaTeX
.SH "BENUTZUNG"
.B exceltex [\-h] [\-c] [\-M \-F \-F \-C \-p] file[.tex]

.SH "BESCHREIBUNG"
Exceltex ist ein LaTeX Paket und Hilfsprogramm mit dem man sehr einfach aus LaTeX auf Zellen in Exceldateien zugreifen kann.
.SH "OPTIONEN"
.TP 
\-h|\-\-help
zeigt Hilfe
.TP 
\-v|\-\-version
zeigt Programmversion
.TP
\-c|\-\-cleanup
entferne von exceltex angelegte temporäre Dateien für file.tex
.TP 
\-m|\-\-nomath
schaltet Vereinfachung von Zahlen in Wissenschaftlicher Notation aus
.TP 
\-f|\-\-noformat
keine Formatierungen anwenden
.TP 
\-n|\-\-nocolor
keine Farben verwenden
.TP 
\-p|\-\-plain
schaltet \-m \-f und \-n ein

.SH "LATEX KOMMANDOS"
.PP 
Exceltex bietet zwei Kommandos um auf einzelne Zellen und auf Tabellen zuzugreifen. Dazu muss das Paket exceltex mit \\usepackage{exceltex} geladen werden.
.TP 
.B \\\inccell{bla.xls!Ergebnisse!B9}
fügt Zelle
.B B9
vom Arbeitsblatt
.B Ergebnisse
aus der Datei
.B bla.xls
ein.
.TP 
.B \\\inctab{bla.xls!Ergebnisse!B2!C15}
Fügt die 14 Zeilen zwischen
.B B2
(oben links) und
.B F15
(unten rechts)
aus dem Arbeitsblatt
.B Ergebnisse
der Datei
.B bla.xls
ein.
.TP 
Bei beiden Kommandos kann der Dateiname (bla.xls) auch weggelassen werden, falls er bis auf die Extension gleich (bla) dem der LaTeX Datei (bla.tex) ist.

.SH "BENUTZUNG"
.TP
Innerhalb des LaTeX Dokuments \\incell und \\inctab verwenden. Dann latex aufrufen, danach exceltex und nochmal latex.
.TP
Siehe auch README (/usr/share/doc/exceltex/README bei Debian) für weitere Beispiele.
.SH "EXIT STATUS"
.TP
Exceltex beendet mit Status 0 falls keine Fehler oder Warnungen aufgetreten sind. Bei Warnungen beendet es mit 1, nach Fehlern mit 2. 

.SH ANFORDERUNGEN
Exceltex benötigt das Perlmodul
.B Spreadsheet::ParseExcel
und die LaTeX Pakete
.B ulem
und
.B color.

.SH PROBLEME
Abgesehen von eigenen Bugs treffen für exceltex auch die Einschränkungen und Probleme von Spreadsheet::ParseExcel zu.

.SH "COPYRIGHT"
.TP 
Copyright (c) 2004\-2006  Hans\-Peter Doerr
.TP 
Exceltex  is  distributed under  the  terms  of the GNU GENERAL PUBLIC LICENSE.

.TP 
This is free software; see the source for copying conditions.  There is NO  warranty;  not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH "AUTHOR"
geschrieben von Hans\-Peter Doerr <doerr@cip.physik.uni\-freiburg.de>
