.TH "EXCELTEX" "1" "2/2005" "Hans-Peter Doerr" ""
.SH "NAME"
exceltex \- fügt Zellen aus Excel-Dateien in LaTeX Dokumente ein.
.SH "SYNTAX"
\fBexceltex\fR [Optionen] Datei
.SH "BESCHREIBUNG"
.LP
Mit Exceltex kann man ganz einfach einzelne- oder Zellen-Bereiche aus MS Excel Dateien in LaTeX Dokumente einfügen.
.LP 
LaTeX hat den Nachteil, dass man externe Daten vor dem einbinden ins Dokument meist erst mühsam von Hand in das richtige Format bringen muss. 
.LP 
Exceltex nimmt einem diese Arbeit zumindest für Tabellenkalkulationen ab, bzw. für Tabellenkalkulationen, die in M$ Excel Dateien vorliegen.

.LP 
Exceltex besteht aus einem LaTeX\-Paket und einem Perlskript. Das LaTeX\-Paket stellt zwei Kommandos für LaTeX zum einfügen von einzelnen Zellen und Zellen\-Bereichen zur Verfügung. Das Perlskript dient zum extrahieren der gewünschten Daten aus einer Exceldatei.

.LP 
Insbesondere, da es sich vorweigend um ein Linuxprogramm handelt, kann man sich fragen, warum exceltex so heisst, und warum es tatsächlich auch nur mit Exceldateien umgehen kann. Die Antwort ist einfach die, dass ich damals nur ein Perlkaket zum lesen von Exceldateien gefunden habe. Das Excelformat wird aber von praktisch allen Tabellenkalkulationsprogrammen unterstütz, und sollte daher kein allzu großes Problem sein. Aussdem enthält das Excelformat in der Standardeinstellung auch die Resultate von Rechnungen, was z.B. Gnumeric leider anscheinend nicht macht.


.SH "OPTIONEN"
.TP 
\fB\-c|\-\-cleanup\fR
löscht temporäre, von exceltex angelegte, Dateien.
.SH "LATEX-KOMMANDOS"
.LP 
Exceltex bietet zum Einfügen von einzelnen Zellen oder ganzen Zellenbereichen zwei neue Kommandos für LaTeX.

.TP 
\fB\\inccell{Datei!Blatt!Zelle}\fR
Fügt die Zelle 'Zelle' aus dem Blatt 'Blatt' der Datei 'Datei' an der aktuellen Stelle ins LaTeX\-Dokument ein. Falls der Dateiname der LaTeX\-Datei gleich dem der Exceldatei ist (von der Endung abgesehen), kann 'Datei' auch weggelassen werden: \fB\\inccell{Blatt!Zelle}\fR. 'Zelle' wird in den üblichen Koordinaten für Tabellenkalkulationsprogramme angegeben, z.B . A1 oder Z23.


.TP 
\fB\\incctab{Datei!Blatt!Zelle1!Zelle2}\fR
Fügt mehrere Zellen im Bereich zwischen 'Zelle1' (linke, obere Ecke) und 'Zelle2' (rechte, untere Ecke) an der aktuellen Stelle ein. Die einzelnen Zellen werden dabei durch ein & getrennt. Für Datei gilt dabei das gleiche wie für \\inccell{}.
.SH "BENUTZUNG"
.LP 
Markiere einzelne Zellen und/oder Zellbereiche wie im Abschnitt LATEX\-KOMMANDOS angegeben

.LP 
Ein erster latex\-Lauf erzeugt eine Indexdatei, aus der das exceltex Perlskript die Angaben über die einzufügenden Zellen auslesen kann. Nach diesem latex\-Lauf holt ein Aufruf von exceltex die benötigten Daten aus der Exceldatei und speichert sie einzeln in durchnummerrierten Dateien. Diese Dateien werden beim darauf folgenden, zweiten latex\-Lauf einfach mit dem \\input{}\-Kommando von LaTeX eingelesen.
.SH "VORRAUSSETZUNGEN"
Das exceltex Perlskript benötigt das \fBSpreadsheet::ParseExcel\fR Perl\-Paket.
.SH "BESCHRÄNKUNGEN"
Exceltex benutzt SpreadSheet::ParseExcel zum lesen der Exceldateien, und unterliegt damit den gleichen Problemen und Einschränkungen. Z.B. können nur Dateien gelesen werden, die die Resultate von Rechnungen mit abspeichern, was nicht immer der Fall sein muss. Aus diesem Grund können z.B. keine von SpreadSheet::WriteExcel erzeugten Dateien gelesen werden.
.SH "DATEIEN"
.TP 
\fBexceltex.sty\fR
enthält das LaTeX Package zu exceltex
.SH "COPYRIGHT"
Copyright (C) 2004,2005 Hans\-Peter Doerr
.br 
exceltex is distributed under the terms of the GNU GENERAL PUBLIC LICENSE

This is free software; see the source for copying conditions.  There is NO  warranty;  not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "AUTOR"
geschrieben von Hans\-Peter Doerr <doerr@cip.physik.uni\-freiburg.de>
